#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Error: you must provide exactly one argument"
    exit 1
fi

if ! [[ "$1" =~ ^[a-zA-Z0-9_\.\-]+\.git$ ]]; then
    echo "Error: invalid repo name"
    exit 1
fi

repo_dir="/git/$1"
if [ -e "$repo_dir" ]; then
    echo "Error: repo already exists"
    exit 1
fi

mkdir "$repo_dir"
git --bare init "$repo_dir"
